# Generated by Django 5.1.4 on 2024-12-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDescription', models.CharField(max_length=50)),
                ('lCurrent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNomDestino', models.CharField(max_length=50)),
                ('cDescriptionDestino', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lCurrent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDescription', models.CharField(max_length=50)),
                ('lCurrent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destino')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lugar')),
            ],
        ),
    ]
