# Generated by Django 5.1.4 on 2024-12-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='cDescriptionDestino',
            field=models.TextField(),
        ),
    ]
