# Generated by Django 5.1.4 on 2024-12-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_destino_cdescriptiondestino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curl', models.CharField(max_length=100)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Incluye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDescription', models.CharField(max_length=250)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cHora', models.CharField(max_length=10)),
                ('cDescription', models.CharField(max_length=100)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destino')),
            ],
        ),
        migrations.CreateModel(
            name='NoIncluye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDescription', models.CharField(max_length=100)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Ofrece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDescription', models.CharField(max_length=100)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destino')),
            ],
        ),
    ]
