# Generated by Django 5.1.4 on 2024-12-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagen_incluye_itinerario_noincluye_ofrece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='curl',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
